export const ADD_MESSAGE = "ADD_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const SHOW_DETAIL = "SHOW_DETAIL";
export const INITIAL_MESSAGES = "INITIAL_MESSAGES";
export const ADD_USER = "ADD_USER";